name: Update README.md

on:
  push:
    # only triggered when pushing to main branch
    branches:
      - main
  schedule:
    # be triggered at 5am every day
    - cron: "0 5 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install
      - name: Generate github profile
        run: |-

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_TOKEN: ${{ secrets.WAKATIME_TOKEN }}
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "peizhenliao23@gmail.com"
          git config --global user.name "Peizhen Liao"
          git pull
          git add -A
          git commit -m "Daily: update README.md" || exit 0
          git push
